// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEFP1nNwSCuOJRVGWA66GWht76dQugrNo',
    appId: '1:604078143609:web:27e4ac125b76423b047ca8',
    messagingSenderId: '604078143609',
    projectId: 'mobiledevicesfirebase',
    authDomain: 'mobiledevicesfirebase.firebaseapp.com',
    storageBucket: 'mobiledevicesfirebase.appspot.com',
    measurementId: 'G-H5WP5KC4QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWAsrxau7WLcYeTnWw2dXSBkHAEiVbfI',
    appId: '1:604078143609:android:caab91532597370f047ca8',
    messagingSenderId: '604078143609',
    projectId: 'mobiledevicesfirebase',
    storageBucket: 'mobiledevicesfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5eezRsjkzK4Y4ozFxQz25RbhWkkxNDM',
    appId: '1:604078143609:ios:1fc49e4358f4d137047ca8',
    messagingSenderId: '604078143609',
    projectId: 'mobiledevicesfirebase',
    storageBucket: 'mobiledevicesfirebase.appspot.com',
    iosClientId: '604078143609-kf1cn7ui72ptn25q0mmvtkherf1aagp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileDevicesFirebaseTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ5eezRsjkzK4Y4ozFxQz25RbhWkkxNDM',
    appId: '1:604078143609:ios:1fc49e4358f4d137047ca8',
    messagingSenderId: '604078143609',
    projectId: 'mobiledevicesfirebase',
    storageBucket: 'mobiledevicesfirebase.appspot.com',
    iosClientId: '604078143609-kf1cn7ui72ptn25q0mmvtkherf1aagp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileDevicesFirebaseTasks',
  );
}
